CREATE TABLE TEMPO_D (
	TEMPO_ID DATE,
	ANO INTEGER,
	MES INTEGER,
	DIA INTEGER,
	DIA_SEMANA INTEGER,
	DIA_ANO INTEGER,
	ANO_BISSEXTO BOOLEAN,
	DIA_UTIL BOOLEAN,
	FIM_SEMANA BOOLEAN,
	FERIADO BOOLEAN,
	NOME_DIA_SEMANA VARCHAR(15),
	NOME_DIA_SEMANA_ABREV VARCHAR(15),
	NOME_MES VARCHAR(15),
	NOME_MES_ABREV VARCHAR(15),
	QUINZENA INTEGER,
	BIMESTRE INTEGER,
	TRIMESTRE INTEGER,
	SEMESTRE INTEGER,
	NR_SEMANA_MES INTEGER,
	NR_SEMANA_ANO INTEGER,
	ESTACAO_ANO VARCHAR(15),
	DATA_POR_EXTENSO VARCHAR(50),
	constraint TEMPO_D_PK primary key (TEMPO_ID)
);

DESCRIBE TEMPO_D;
